# Generated by Django 5.1 on 2024-09-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_message_unread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
