# Generated by Django 5.1 on 2024-08-13 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username must only include alphanumericals, "-" and "_" .', regex='^[a-zA-Z0-9_-]+$')]),
        ),
    ]
