# Generated by Django 5.1 on 2024-09-10 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_alter_message_unread'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField()),
                ('participants', models.ManyToManyField(blank=True, related_name='gc_participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
