# Generated by Django 5.1 on 2024-08-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_follower'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('user', 'follower')},
        ),
    ]
