# Generated by Django 5.1 on 2024-09-10 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0004_groupconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Message...')),
                ('date_time', models.DateTimeField()),
                ('unread', models.BooleanField(default=True)),
                ('gc_message_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gc_message_from', to=settings.AUTH_USER_MODEL)),
                ('group_chat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_chat', to='socials.groupconversation')),
            ],
        ),
    ]
