# Generated by Django 5.1 on 2024-08-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0004_alter_follower_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('user2', 'user1')},
        ),
    ]
