# Generated by Django 5.1 on 2024-09-10 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0005_gcmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcmessage',
            name='unread',
        ),
        migrations.AddField(
            model_name='gcmessage',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='seen_group_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
