# Generated by Django 5.1 on 2024-08-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0005_alter_friendship_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('user1', 'user2')},
        ),
    ]
