# Generated by Django 5.1 on 2024-08-14 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0005_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Please enter a valid last name', regex='^[a-zA-Z]+$')]),
        ),
    ]
