# Generated by Django 5.1 on 2024-08-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0006_alter_friendship_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='media/default_things/default_profile_image.jpg', upload_to='profile_pictures'),
        ),
    ]
